### ISSUE TITLE
You might really like the old yhchang stuff

### ISSUE THREAD

**Issue by nelsonpecora** [markmarkoh/birdman#2]
So, during the web 1.0 era, an art group in Seoul called [Young-Hae Chang Heavy Industries](http://en.wikipedia.org/wiki/Young-Hae_Chang_Heavy_Industries) put up a bunch of neat little multimedia poems. The Birdman credits sequence is eerily reminiscent of their style, though less harshly minimalist. They were working primarily in Flash and had hardcoded animations (rather than generating them from the music), but I think you'd enjoy some of their work. Thankfully it's still online! http://www.yhchang.com/

**Comment by markmarkoh** [comment]
@yoshokatana Thanks for the link! These are really neat.
